export enum PokemonTypesEnum {
    Bug = 'bug',
    Dark = 'dark',
    Dragon = 'dragon',
    Eletric = 'electric',
    Fairy = 'fairy',
    Fighting = 'fighting',
    Fire = 'fire',
    Flying = 'flying',
    Ghost = 'ghost',
    Grass = 'grass',
    Ground = 'ground',
    Ice = 'ice',
    Normal = 'normal',
    Poison = 'poison',
    Psychic = 'psychic',
    Rock = 'rock',
    Steel = 'steel',
    Water = 'water',
}